// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/sentinel-official/hub/x/swap/types
// ALIASGEN: github.com/sentinel-official/hub/x/swap/keeper
package swap

import (
	"github.com/sentinel-official/hub/x/swap/keeper"
	"github.com/sentinel-official/hub/x/swap/types"
)

const (
	EthereumHashLength  = types.EthereumHashLength
	AttributeKeyTxHash  = types.AttributeKeyTxHash
	AttributeKeyAddress = types.AttributeKeyAddress
	AttributeKeyAmount  = types.AttributeKeyAmount
	ModuleName          = types.ModuleName
	QuerierRoute        = types.QuerierRoute
	DefaultParamspace   = types.DefaultParamspace
	DefaultSwapEnabled  = types.DefaultSwapEnabled
	DefaultSwapDenom    = types.DefaultSwapDenom
	DefaultApproveBy    = types.DefaultApproveBy
	QuerySwap           = types.QuerySwap
	QuerySwaps          = types.QuerySwaps
)

var (
	// functions aliases
	RegisterLegacyAminoCodec                = types.RegisterLegacyAminoCodec
	RegisterInterfaces                      = types.RegisterInterfaces
	BytesToHash                             = types.BytesToHash
	NewGenesisState                         = types.NewGenesisState
	DefaultGenesisState                     = types.DefaultGenesisState
	SwapKey                                 = types.SwapKey
	NewMsgSwapRequest                       = types.NewMsgSwapRequest
	NewMsgServiceClient                     = types.NewMsgServiceClient
	RegisterMsgServiceServer                = types.RegisterMsgServiceServer
	NewParams                               = types.NewParams
	DefaultParams                           = types.DefaultParams
	ParamsKeyTable                          = types.ParamsKeyTable
	NewQuerySwapRequest                     = types.NewQuerySwapRequest
	NewQuerySwapsRequest                    = types.NewQuerySwapsRequest
	NewQueryServiceClient                   = types.NewQueryServiceClient
	RegisterQueryServiceServer              = types.RegisterQueryServiceServer
	RegisterQueryServiceHandlerServer       = types.RegisterQueryServiceHandlerServer
	RegisterQueryServiceHandlerFromEndpoint = types.RegisterQueryServiceHandlerFromEndpoint
	RegisterQueryServiceHandler             = types.RegisterQueryServiceHandler
	RegisterQueryServiceHandlerClient       = types.RegisterQueryServiceHandlerClient
	NewKeeper                               = keeper.NewKeeper

	// variable aliases
	ModuleCdc                      = types.ModuleCdc
	ErrorMarshal                   = types.ErrorMarshal
	ErrorUnmarshal                 = types.ErrorUnmarshal
	ErrorUnknownMsgType            = types.ErrorUnknownMsgType
	ErrorUnknownQueryType          = types.ErrorUnknownQueryType
	ErrorInvalidField              = types.ErrorInvalidField
	ErrorSwapIsDisabled            = types.ErrorSwapIsDisabled
	ErrorUnauthorized              = types.ErrorUnauthorized
	ErrorDuplicateSwap             = types.ErrorDuplicateSwap
	EventTypeSet                   = types.EventTypeSet
	ErrInvalidLengthGenesis        = types.ErrInvalidLengthGenesis
	ErrIntOverflowGenesis          = types.ErrIntOverflowGenesis
	ErrUnexpectedEndOfGroupGenesis = types.ErrUnexpectedEndOfGroupGenesis
	ParamsSubspace                 = types.ParamsSubspace
	RouterKey                      = types.RouterKey
	StoreKey                       = types.StoreKey
	PrecisionLoss                  = types.PrecisionLoss
	EventModuleName                = types.EventModuleName
	SwapKeyPrefix                  = types.SwapKeyPrefix
	ErrInvalidLengthMsg            = types.ErrInvalidLengthMsg
	ErrIntOverflowMsg              = types.ErrIntOverflowMsg
	ErrUnexpectedEndOfGroupMsg     = types.ErrUnexpectedEndOfGroupMsg
	KeySwapEnabled                 = types.KeySwapEnabled
	KeySwapDenom                   = types.KeySwapDenom
	KeyApproveBy                   = types.KeyApproveBy
	ErrInvalidLengthParams         = types.ErrInvalidLengthParams
	ErrIntOverflowParams           = types.ErrIntOverflowParams
	ErrUnexpectedEndOfGroupParams  = types.ErrUnexpectedEndOfGroupParams
	ErrInvalidLengthQuerier        = types.ErrInvalidLengthQuerier
	ErrIntOverflowQuerier          = types.ErrIntOverflowQuerier
	ErrUnexpectedEndOfGroupQuerier = types.ErrUnexpectedEndOfGroupQuerier
	ErrInvalidLengthSwap           = types.ErrInvalidLengthSwap
	ErrIntOverflowSwap             = types.ErrIntOverflowSwap
	ErrUnexpectedEndOfGroupSwap    = types.ErrUnexpectedEndOfGroupSwap
)

type (
	EthereumHash                    = types.EthereumHash
	GenesisState                    = types.GenesisState
	MsgSwapRequest                  = types.MsgSwapRequest
	MsgSwapResponse                 = types.MsgSwapResponse
	MsgServiceClient                = types.MsgServiceClient
	MsgServiceServer                = types.MsgServiceServer
	UnimplementedMsgServiceServer   = types.UnimplementedMsgServiceServer
	Params                          = types.Params
	QuerySwapsParams                = types.QuerySwapsParams
	QuerySwapsRequest               = types.QuerySwapsRequest
	QuerySwapRequest                = types.QuerySwapRequest
	QuerySwapsResponse              = types.QuerySwapsResponse
	QuerySwapResponse               = types.QuerySwapResponse
	QueryServiceClient              = types.QueryServiceClient
	QueryServiceServer              = types.QueryServiceServer
	UnimplementedQueryServiceServer = types.UnimplementedQueryServiceServer
	Swaps                           = types.Swaps
	Swap                            = types.Swap
	Keeper                          = keeper.Keeper
	Querier                         = keeper.Querier
)
