name: Tests and Code Coverage

on:
  pull_request:
  push:
    branches:
      - development
      - master

jobs:
  go:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Set Up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.25'

      - name: Generate Coverage Report
        run: |
          make test-coverage
          files=""
          files+=" $(find ./ -type f -name '*.go' -exec grep -l 'DO NOT COVER' {} \;)"
          files+=" $(find ./ -type f -name '*.pb.go')"
          files+=" $(find ./ -type f -name '*.pb.gw.go')"
          files+=" $(find ./ -type f -path '*/client/cli/*')"
          files+=" $(find ./ -type f -path '*/expected/*')"
          files+=" $(find ./ -type f -path '*/services/*')"
          for f in ${files}; do
            f=$(echo "${f}" | sed 's@^.@github.com/sentinel-official/sentinelhub/v[0-9]*@g')
            echo "Excluding file ${f} from coverage report..."
            sed -i "/$(echo "${f}" | sed 's@/@\\/@g')/d" ./coverage.txt
          done

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f #v7.0.0
        with:
          file: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
