// nolint
// autogenerated code using github.com/rigelrozanski/multitool
// aliases generated for the following subdirectories:
// ALIASGEN: github.com/sentinel-official/hub/x/dvpn/provider/keeper
// ALIASGEN: github.com/sentinel-official/hub/x/dvpn/provider/querier
// ALIASGEN: github.com/sentinel-official/hub/x/dvpn/provider/types
package provider

import (
	"github.com/sentinel-official/hub/x/dvpn/provider/keeper"
	"github.com/sentinel-official/hub/x/dvpn/provider/querier"
	"github.com/sentinel-official/hub/x/dvpn/provider/types"
)

const (
	Codespace      = types.Codespace
	ModuleName     = types.ModuleName
	QuerierRoute   = types.QuerierRoute
	RouterKey      = types.RouterKey
	StoreKey       = types.StoreKey
	QueryProvider  = types.QueryProvider
	QueryProviders = types.QueryProviders
)

var (
	// functions aliases
	NewKeeper              = keeper.NewKeeper
	Querier                = querier.Querier
	RegisterCodec          = types.RegisterCodec
	ErrorMarshal           = types.ErrorMarshal
	ErrorUnmarshal         = types.ErrorUnmarshal
	ErrorUnknownMsgType    = types.ErrorUnknownMsgType
	ErrorUnknownQueryType  = types.ErrorUnknownQueryType
	NewGenesisState        = types.NewGenesisState
	DefaultGenesisState    = types.DefaultGenesisState
	ProviderKey            = types.ProviderKey
	NewQueryProviderParams = types.NewQueryProviderParams

	// variable aliases
	ModuleCdc         = types.ModuleCdc
	ProvidersCountKey = types.ProvidersCountKey
	ProviderKeyPrefix = types.ProviderKeyPrefix
)

type (
	Keeper              = keeper.Keeper
	GenesisState        = types.GenesisState
	MsgRegisterProvider = types.MsgRegisterProvider
	Provider            = types.Provider
	QueryProviderParams = types.QueryProviderParams
)
